# Changes here will be overwritten by Copier
_commit: v0.2.1
_src_path: git+https://gitlab.ewi.tudelft.nl/reit/python-package-template
coc: our_coc
email: s.wacker@tudelft.nl
environment_manager: pixi
full_name: Soren Wacker
host: gitlab.ewi.tudelft.nl
license: MIT
min_python_version: '3.12'
org: sdrwacker
project_name: design-patterns
project_short_description: Examples of software design patterns.
python_name: design_patterns
typing: no_typing
url: git@gitlab.ewi.tudelft.nl:sdrwacker/design-patterns.git
